### ISSUE TITLE
Display comments for tokens 

### ISSUE THREAD

**Issue by an-fischer** [VedaWebProject/Tekst#251]
** Feature function **
Allow for token comments (attribute "comment" on token level) to be shown when hovering over the respective token. 

Männi sänks!

**Comment by bkis** [comment]
Addition: Somehow display **all** annotations for a token in browse view on demand.

Idea:
1. Hint to token comment with a small badge on the token object
2. Add tooltip text to token object: "_Show all available annotations_" + (if token has comment) "_(annotation contains a comment)_"
3. A click on the token object opens a modal showing **all** the annotations and (more prominent) the comment (if any)
