### ISSUE TITLE
Deepl translation link using wrong parameter format

### ISSUE THREAD

**Issue by an-fischer** [VedaWebProject/Tekst#409]
When clicking on the icon for translating a resource, the following relevant information is not sent to deepl: the text to be translated; respective source language of the text; the target language selected in the test instance.

**Comment by bkis** [comment]
Good catch! There _is_ a bug, but it seems that something else is causing it:

The information _is_ passed. For example, the **English** language text _"This is a test."_, requesting a translation to **German** would produce the following URL:
```
https://www.deepl.com/en/translator#EN/DE/This%20is%20a%20test.
```
So it's all there.

**But** DeepL seems to have changed its API and the URL now **should look like this**:
```
https://www.deepl.com/en/translator#en/de/This%20is%20a%20test.
```

Basically, the language codes are now lower-cased (which better conforms to standards, I suppose) and they added some specifiers for regional language variants, like `pt-pt` and `pt-br`.

Also, there seem to be [different sets of language codes for source and target languages](https://developers.deepl.com/docs/resources/supported-languages) – we'll have to take that into account (At the time of this comment, the codes are still upper-cased in the documentation).

I will update these language codes – I guess that's all it takes. Thank you for pointing this out!
