### ISSUE TITLE
Small suggestion for change of wording in "advanced search"

### ISSUE THREAD

**Issue by an-fischer** [VedaWebProject/Tekst#435]
Hello Börge! We have a small suggestion for changing the wording in the "advanced search" for resource type "annotation": There is the option "create" / "erstellen" for selecting an attribute/annotation for the search. We suggest changing it to "select" / "auswählen" or something similar so that it is different from the view where new annotations are (literally) created or added. What do you think?

**Comment by bkis** [comment]
Will do!

**Comment by an-fischer** [comment]
Nice, thank you!
