### ISSUE TITLE
Search results: Display title of (child) location

### ISSUE THREAD

**Issue by an-fischer** [VedaWebProject/Tekst#436]
Hello Börge, as briefly discussed yesterday: In the listing of search results, for each search result the location title gets displayed (Nice!). In the VedaWeb test instance, this is just the number of the stanza since our stanzas have no title. Should we add the name of the (child) location for user orientation? E.g. "stanza: 4" instead of "4"?

**Comment by bkis** [comment]
I found an even better way: It is now configurable (per text) whether the full location label (e.g. `1.2.3` as opposed to just `3`) should be used as the title of a search result.
