### ISSUE TITLE
Advanced search: Submit search form via Enter key

### ISSUE THREAD

**Issue by an-fischer** [VedaWebProject/Tekst#440]
Hello again, while testing our VedaWeb instance, one of our colleagues expressed the wish to be able to submit searches directly by hitting the Enter key. I really do not know about the pros and cons of "submit via enter", so I'll just forward the message 🙂

**Comment by bkis** [comment]
I guess this is about the "advanced search", right? It's a tricky topic, as the Enter key has several other functions in such a complex form, like selecting a value from a list etc.
If the form submits when I just want to select a value from a list, this would break keyboard control of the form. Let's discuss this in detail later, but I already had to reject the same request for the old platform for this reason.

**Comment by an-fischer** [comment]
Yeah, sounds tricky! Thanks for the heads-up!

**Comment by bkis** [comment]
For the reasons explained above, I will solve this with a compromise: The "advanced" search will be executable via a hotkey (<kbd>Ctrl</kbd>+<kbd>Enter</kbd>). That's all I can do, unfortunately.

**Comment by an-fischer** [comment]
I think this is a great compromise, thanks again!
