### ISSUE TITLE
Resource type "annotation": Copy token or glossing without opening the detailed view

### ISSUE THREAD

**Issue by an-fischer** [VedaWebProject/Tekst#441]
Hello again, while testing our VedaWeb instance (resource type annotation), one of our colleagues expressed the wish to be able to copy parts of the glossing, e.g. copy the token directly, without automatically opening the detailed view. Could this be like a "long press" option or something the like?

**Comment by bkis** [comment]
Maybe I could even manage to make a right-click context menu work... So people have the option to copy the token or token + annotation (`token (anno, anno, ...)`) etc.

**Comment by an-fischer** [comment]
Sounds good, thank you!

**Comment by an-fischer** [comment]
Just checked it out. I really like the right-click solution with the two options (token/+glossing), thank you!
